version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGERS_PASSWORD=$db_password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=localhost
      - PORT=8080
    depends_on: [db]
    network_mode: host
  db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    volumes: 
      - beacon_api_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$db_password
      - POSTGRES_DB=postgres
    network_mode: host
      

volumes:
  beacon_api_volume: {}

